[workspace]
authors = ["Johannes Koester <johannes.koester@uni-due.de>"]
channels = ["conda-forge", "bioconda"]
name = "snakemake-workflow-catalog"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
jinja2 = ">=3.1.4,<4.0"
pygithub = ">=2.5.0,<3.0"
gitpython = ">=3.1.43,<4.0"
snakemake = ">=9.1"
snakefmt = ">=0.11,<0.12"
python = ">=3.12,<3.13"
ratelimit = ">=2.2.1,<3.0"
mdutils = ">=1.6.0,<2.0"
sphinx = ">=7.2.6,<8.0"
sphinxawesome-theme = ">=5.2.0,<6.0"
sphinx-design = ">=0.6.1,<0.7"
myst-parser = ">=4.0.1,<5.0"
altair = ">=5.5.0,<6.0"
sphinxcontrib-jquery = ">=4.1.0,<5.0"
sphinx-datatables = ">=1.0.0,<2.0"
sphinxext-altair = ">=0.2.0,<0.3"

[tasks]
test-generate-catalog = { cmd = "python scripts/generate-catalog.py", env = { OFFSET = "0", N_REPOS = "3", LATEST_COMMIT = "7" } }
test-generate-catalog-single-repo = { cmd = "python scripts/generate-catalog.py", env = { TEST_REPO = "snakemake-workflows/dna-seq-varlociraptor" } }
test-cleanup-catalog = { cmd = "python scripts/cleanup-catalog.py", env = { OFFSET = "0", N_REPOS = "3" } }
generate-catalog = { cmd = "python scripts/generate-catalog.py" }
cleanup-catalog = { cmd = "python scripts/cleanup-catalog.py" }
render-catalog = "sphinx-build source build"
