name: Generate catalog

on:
  schedule:
    - cron: 0 5 * * 1
  push:
    branches: [main, dev]

jobs:
  generate-catalog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        offset: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0

      - name: Pull latest changes
        run: |
          git pull --rebase origin ${{ github.ref }}

      - name: generate-catalog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OFFSET: ${{ matrix.offset }}
          LATEST_COMMIT: 7
        run: pixi run generate-catalog

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  cleanup-catalog:
    runs-on: ubuntu-latest
    needs: generate-catalog
    strategy:
      matrix:
        offset: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0

      - name: Pull latest changes
        run: |
          git pull --rebase origin ${{ github.ref }}

      - name: cleanup-catalog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OFFSET: ${{ matrix.offset }}
        run: pixi run cleanup-catalog

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
