name: Generate catalog

on:
  schedule:
    - cron: 0 5 * * 1
  push:
    branches: [main]

jobs:
  generate-catalog:
    if: github.event_name == 'schedule' || github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        offset: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0
        with:
          cache: true

      - name: Upload lockfile
        uses: actions/upload-artifact@v7
        with:
          name: pixi_lock.zip
          path: ./pixi.lock

      - name: Pull latest changes
        run: |
          git pull --rebase origin ${{ github.ref }}

      - name: generate-catalog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OFFSET: ${{ matrix.offset }}
          LATEST_COMMIT: 7
        run: pixi run generate-catalog

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
